//
//  StopMonitorInfoViewController.m
//  MyStopMonitor
//
//  Created by Eddie Power on 18/06/2014.
//  Copyright (c) 2014 Eddie Power. All rights reserved.
//

#import "StopMonitorInfoViewController.h"

@interface StopMonitorInfoViewController ()

@end

@implementation StopMonitorInfoViewController


- (void)viewDidLoad
{
    [super viewDidLoad];
    
    
    
    //Set up the text to show when the user selects the segment control
    self.welcomeText = @"Thank you for downloading my application myStopMonitor, I have looked at what friends family and my own expierences with missing my stop on the train because of working on a laptop, playing a game on a phone, listening to music too loudly and not hearing announcments of stations or simply bieng exausted and falling asleep.  I included features in this version of the application to help prevent this, the location of the stops on the train line selected are automattically generated by checking with the PTV servers meaning theres no possible way to get the stop location wrong, then the user can select the stop and view details about this stop like when the next trains are due to arrive to help provide a time for arrival, you can also activate or de activate alerts for different stops so you can set your home stop and a work stop at the same time and choose which to use by setting the switch, the app will notify you while your in the application with an alert box, vocal alert and vibration, and a visual alert of the upcoming stop name, The application will also notify you if your listening to music and have the app running in the background with a message on screen via notification center and an audio alert, another feature of this app is that even if it has been shut down it will still let you know that the stop is coming up and will then launch the app so you can de activate this alert to stop any unwanted alerts happening.  I will continue to add new features to updates to the app and would love to hear feedback from users through the app store or via mailto:myStopMonitor@gmail.com I will take into account all ideas and design changes.";
    
    self.aboutText = @"About myStopMonitor  (c) 2014. Eddie Power.";
    
    
    // Do any additional setup after loading the view.
    switch (self.infoTextSegment.selectedSegmentIndex)
    {
        case 0:
            self.infoTextView.text = self.welcomeText;
            break;
        case 1:
            self.infoTextView.text = self.aboutText;
            break;
        default:
            break;
    }
    
}


- (IBAction)indexChanged:(UISegmentedControl *)sender
{
    switch (self.infoTextSegment.selectedSegmentIndex)
    {
        case 0:
            self.infoTextView.text = self.welcomeText;
            break;
        case 1:
            self.infoTextView.text = self.aboutText;
            break;
        default: 
            break; 
    }
}
@end
